apiVersion: v1
kind: Pod
metadata:
  labels:
    app: training
    name: "{task_name}"
    user_id: "{user_id}"
  name: "{training-name}"
  namespace: training
spec:
  restartPolicy: Never
  containers:
  - image: harbor.pinlandata.com/pinlan/pinshi:model-zoo-dev-v0.1
    name: training
    resources:
      limits:
        cpu: "1000m"
        memory: "1Gi"
      requests:
        cpu: "1000m"
        memory: "1Gi"

